Sprint/1
Devstock-Academy/PPD-Sebastian-Daszewski pull request #4
Opened 2023-08-24 12:01 UTC by SebastianDaszewski

2023-08-29 10:15 UTC, SebastianDaszewski commented
Can you please tell me what I exactly need to change? Background color in social media bar? I can't see more differences on my screen.

2023-08-29 19:42 UTC, SebastianDaszewski commented
Please take a look now.

2023-09-02 15:53 UTC, elstyropiano requested changes
Remember to change ci.yml file becasuse now we have build error:
![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/b2e7f99e-75da-4749-a0c7-ae9cba003c73)
Rafał explained how to do that.

Please add also package like we talk on slack:
![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/404fdc70-9476-454a-9b1b-be6dbd2d9ecc)
Please remember this site should be responsive from 1024 px
![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/3aef7e6d-dc36-44f2-b0d9-a9c206249030)

![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/7ed5e4d0-a512-4c34-8b70-897c6323ca38)
![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/30b11fb7-26ff-4322-9d54-27642091b28e)
![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/20cbcc89-391d-4a2d-819e-b45b8c15f5ad)
![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/972b87fb-0886-4b6c-9126-b75560c256d0)


- Please apply styles in your project so that they are consistent with the graphic design. You can trace point by point whether all elements on the page have been included and whether the size spacing and colors are correct

2023-09-02 16:01 UTC, elstyropiano commented
remember to use clsx library in case like that 
![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/cdb4ba4a-e833-4a03-918e-62834f4566b3)
It was was included in docs https://trello.com/c/rxvtwg22/6-docs

If you are not use some variables or props like here, please don't leave like that, just remove it :
![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/1daf4ff0-806a-4fff-95cc-18c6f18ef15e)

2023-09-11 07:32 UTC, elstyropiano requested changes
It's looks better than before but we have to correct some places :

- Please use `font-family: Lexend Deca;`
- padding should equal 40 px, also in social media, now is not in one line 

![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/84574c42-4a82-4622-b890-1fc7f2ebc827)
![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/97f0d432-66b3-40ac-a381-4c0678685e54)

- Please correct modal

![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/f13dcf4d-e032-487d-a846-8a8949deafe8)

- something is wrong with that place on big screen, footer should be on the bottom, the same in another routes:

![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/4e0f7f5a-eb5a-4541-865d-a7da6de8ea4a)

- When we go to the login or registration page, many errors appear. So please fix that 
![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/7c963377-fb0a-43e2-b030-11832f931fbd)

- we have  no /landing route :
![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/2dce0fcb-7b9f-464a-b4fa-d8805865d9ec)

![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/0ab338ae-d809-4ccb-97e4-d3612c4bcb5e)

- Please write docks , and correct files 
![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/48022b99-6075-430f-b051-c3b51e945dfe)

- When i click on submit button, errors should appear : 
![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/47f563ee-8326-4bec-b6e9-b2df2faa1905). But now we have default. In registration form also

2023-09-11 07:32 UTC, elstyropiano commented on app/[locale]/login/page.tsx
> +export default function Page() {
Please use only arrow functions, move export also in down below component. `Page=> LoginPage`.According to the documentation you should return here </Login> , correct also it in registration and landing(after create it) routes

2023-09-11 07:32 UTC, elstyropiano commented on app/[locale]/login/page.tsx
> +          wrongEmail={l("wrongEmail")}
Do you need pass props here ?

2023-09-11 07:32 UTC, elstyropiano commented on app/[locale]/login/page.tsx
> +  const l = useTranslations("loginForm");
Please use only one translation for file

2023-09-11 07:32 UTC, elstyropiano commented on app/[locale]/login/page.tsx
> +    <>
Do we need that react fragment ?

2023-09-11 07:32 UTC, elstyropiano commented on app/[locale]/page.tsx
> +
Please don't leave spaces in jsx

2023-09-11 07:32 UTC, elstyropiano commented on app/[locale]/login/page.tsx
> +        />{" "}
Please dont leave elements like that `{" "}`. Aplly it to all files

2023-09-11 07:32 UTC, elstyropiano commented on app/[locale]/registration/page.tsx
> +        <RegistrationForm
I think u don't need pass props like that

2023-09-11 07:32 UTC, elstyropiano commented on features/home/components/.Header.tsx.swp
Do you need that file  ?

2023-09-11 07:32 UTC, elstyropiano commented on features/home/components/ConfirmModal.tsx
> +import React from "react";
I think you don't need that import

2023-09-11 07:32 UTC, elstyropiano commented on features/home/components/ConfirmModal.tsx
> +    <>
I think you don't need that

2023-09-11 07:32 UTC, elstyropiano commented on features/home/components/Content.tsx
> +  const shouldShowImageOnLeft = !isTextPresent;
something is wrong here if is true
![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/8f430609-b17f-4d70-a80b-8262045859b4)

2023-09-11 07:32 UTC, elstyropiano commented on features/home/components/Content.tsx
> +                  "font-lexend-deca tracking-wider text-black w-520 font-thin 1024:leading-24px  1024:w-400 1024:text-14px 1366:w-520 1366:mt-5 1366:text-20px 1366:leading-30px ",
Spaces also, please check your files and correct.

2023-09-11 07:32 UTC, elstyropiano commented on features/home/components/Content.tsx
> +type Props = {
Please check docs and write how to names type

2023-09-15 09:56 UTC, elstyropiano requested changes
Looks better but please apply all advices from previous review: 
![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/e478fae3-95f8-4c50-918c-e481449766ef)
![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/d0d67d5c-7038-4aa9-a4d1-1ee408c94c0b)
![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/3cb5eb74-20ad-418f-b4b0-77589c8754c2)

- Button should be higher

![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/59c3eea2-a7bc-44b0-a7d3-710a9a9636f5)

2023-09-15 09:56 UTC, elstyropiano commented on app/[locale]/login/page.tsx
> +    <>
Please follow the previous advice

2023-09-15 09:57 UTC, elstyropiano commented
Please resolve that also :
![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/1f47431d-f97b-49a7-bf86-79a82ea2dee3)

2023-09-15 10:13 UTC, elstyropiano commented
And please resolve build errors 
![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/bf505dca-c2d7-4e71-aac5-35eb324c01e3)

2023-09-22 16:27 UTC, elstyropiano requested changes
Once again ask you to follow the instructions and draw conclusions after the review

2023-09-22 16:27 UTC, elstyropiano commented on app/[locale]/landing/page.tsx
> +import "./../globals.css";
please remove

2023-09-22 16:27 UTC, elstyropiano commented on features/home/components/Content.tsx
> +import Image from "next/legacy/image";
import orders

2023-09-22 16:27 UTC, elstyropiano commented on features/home/components/LoginForm.tsx
> +import Background from "./Background";
import orders

2023-09-22 16:27 UTC, elstyropiano commented on features/home/components/LoginForm.tsx
> +                "w-96 h-10.5 bg-gray-700 border border-gray-600 text-gray-900 text-sm rounded-lg py-3	px-4",
please remove space

2023-09-22 16:27 UTC, elstyropiano commented on features/home/components/LoginForm.tsx
> +            className="mt-7 mb-1 font-medium w-96 h-10 py-2.5	px-5 text-white bg-blue-700 rounded-lg"
same as above

2023-09-22 16:27 UTC, elstyropiano commented on features/home/components/RegistrationForm.tsx
> +import Background from "./Background";
import orders

2023-09-22 16:27 UTC, elstyropiano commented on features/home/components/RegistrationForm.tsx
> +                        "h-10.5 w-76.25 bg-gray-700 border border-gray-600 text-white text-sm leading-4.375 font-normal rounded-lg focus:ring-blue-500 focus:border-blue-500 py-3	px-4",
please remove spaces

2023-09-22 16:27 UTC, elstyropiano commented on features/home/components/RegistrationForm.tsx
> +                        "h-10.5 w-76.25 bg-gray-700 border border-gray-600 text-white text-sm/4.375 font-normal rounded-lg focus:ring-blue-500 focus:border-blue-500 py-3	px-4",
same here

2023-09-22 16:27 UTC, elstyropiano commented on features/home/components/RegistrationForm.tsx
> +                    "h-10.5 w-159 bg-gray-700 border border-gray-600 text-white text-sm/4.375 rounded-lg focus:ring-blue-500 focus:border-blue-500 block py-3	px-4",
here also

2023-09-22 16:27 UTC, elstyropiano commented on features/home/components/RegistrationForm.tsx
> +                    "h-10.5 w-159 bg-gray-700 border border-gray-600 text-white text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 py-3	px-4",
here also

2023-09-22 16:27 UTC, elstyropiano commented on features/home/components/TopBar.tsx
> +import Image from "next/image";
import orders

2023-09-22 16:27 UTC, elstyropiano commented on tailwind.config.js
> +      },
please remove unecessary sizes

2023-09-22 16:30 UTC, elstyropiano commented
![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/79022749-ac9b-4fd3-94c4-3a3abd5b6207)
Please don't use square brackets in style

2023-09-22 16:37 UTC, elstyropiano commented
- Please take this into consideration as well

![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/51061e25-5b09-44a9-8b3a-f96da4b1ce2c)

2023-09-23 18:18 UTC, elstyropiano approved these changes

2023-09-27 06:10 UTC, elstyropiano requested changes
![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/ff3fe2fa-105d-4cad-a3fc-a367994b483f)

2023-09-27 06:10 UTC, elstyropiano commented on features/landing/components/Landing.tsx
> +  const l = useTranslations("Content");
`l=>t`

2023-09-27 06:10 UTC, elstyropiano commented on features/login/components/LoginForm.tsx
> +import { zodResolver } from "@hookform/resolvers/zod";
its import from package

2023-09-27 06:10 UTC, elstyropiano commented on features/register/components/RegistrationForm.tsx
> +import { zodResolver } from "@hookform/resolvers/zod";
same here

2023-09-27 06:10 UTC, elstyropiano commented on features/register/components/RegistrationForm.tsx
> +                        "h-10.5 w-76.25 bg-gray-700 border border-gray-600 text-white text-sm/4.375 font-normal rounded-lg focus:ring-blue-500 focus:border-blue-500 py-3	px-4",
???
![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/7e5ab35c-5247-4f02-add0-0ea3ff326479)

2023-09-27 06:10 UTC, elstyropiano commented on features/register/components/RegistrationForm.tsx
> +                        "h-10.5 w-76.25 bg-gray-700 border border-gray-600 text-white text-sm leading-4.375 font-normal rounded-lg focus:ring-blue-500 focus:border-blue-500 py-3	px-4",
![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/a07fb43b-1f18-4417-a506-f4afe9152111)
???

2023-09-27 06:10 UTC, elstyropiano commented on features/register/components/RegistrationForm.tsx
> +                  <div className="mb-7">
What do you think to create reusable component for input ? and use it also in login form its not sense to create every time new input with the same props

2023-09-27 06:10 UTC, elstyropiano commented on features/register/components/RegistrationForm.tsx
> +
??

2023-09-27 06:10 UTC, elstyropiano commented on features/register/components/RegistrationForm.tsx
> +                    "h-10.5 w-159 bg-gray-700 border border-gray-600 text-white text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 py-3	px-4",
??

2023-09-27 06:10 UTC, elstyropiano commented on features/register/components/RegistrationForm.tsx
> +                  <input
Consider about create component for checkbox also

2023-09-27 06:10 UTC, elstyropiano commented on tailwind.config.js
> +        175: "43.75rem",
Please check tailwind docks andremove the styles provided by tailwind

2023-09-29 09:31 UTC, elstyropiano requested changes
- What about it what im wrote in previous review ?

![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/172eda54-7cef-41ae-ada2-1308af5df293)

- Please use svg icons fromat, not jpg

2023-09-29 09:31 UTC, elstyropiano commented on features/landing/components/Landing.tsx
> +import Content from "@/features/landing/components/Content";
Wy import like that ?

2023-09-29 09:31 UTC, elstyropiano commented on features/landing/components/Landing.tsx
> +import { Footer } from "@/components";
You can write it in one line , but i think you don;t need that here. Better to make some shared layout for features beacasue in login and in register code  you import Header and footer also

2023-09-29 09:31 UTC, elstyropiano commented on components/SocialMediaBar.tsx
> +          <a
Please Use Link from next and everywhere where you have <a>

2023-10-07 07:49 UTC, elstyropiano requested changes
- Still we have problem here, if we are on landing route

![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/56a2c8c1-efa9-4fe6-a297-329c9fbd453f)

- Please remove font-lexend-deca from class like here 
![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/9fcf195f-74e6-462b-bb56-ac58e61028b2)
Beacause you defined it in parent 
![image](https://github.com/Devstock-Academy/PPD-Sebastian-Daszewski/assets/96084600/93ab6ec5-8af1-46ee-bd14-13b4e4561e3e)

2023-10-09 09:20 UTC, elstyropiano approved these changes

2023-10-09 12:34 UTC, merged